### ISSUE TITLE
unable to build on Ubuntu 20.04 LTS 

### ISSUE THREAD

**Issue by RockfordWei** [PerfectlySoft/Perfect-NIO#12]
```bash
$ swift test -v
/tmp/Perfect-NIO/.build/checkouts/PerfectLib/Sources/PerfectLib/Dir.swift:130:54: error: cannot find type 'dirent' in scope
    func readDir(_ d: OpaquePointer, _ dirEnt: inout dirent, _ endPtr: UnsafeMutablePointer<UnsafeMutablePointer<dirent>?>!) -> Int32 {
                                                     ^~~~~~
/tmp/Perfect-NIO/.build/checkouts/PerfectLib/Sources/PerfectLib/Dir.swift:130:114: error: cannot find type 'dirent' in scope
    func readDir(_ d: OpaquePointer, _ dirEnt: inout dirent, _ endPtr: UnsafeMutablePointer<UnsafeMutablePointer<dirent>?>!) -> Int32 {
                                                                                                                 ^~~~~~
/tmp/Perfect-NIO/.build/checkouts/PerfectLib/Sources/PerfectLib/Dir.swift:47:13: error: cannot find 'chdir' in scope
                let res = chdir(internalPath)
                          ^~~~~
/tmp/Perfect-NIO/.build/checkouts/PerfectLib/Sources/PerfectLib/Dir.swift:57:8: error: cannot find 'getcwd' in scope
                        _ = getcwd($0.bindMemory(to: Int8.self).baseAddress, 2048)
                            ^~~~~~
/tmp/Perfect-NIO/.build/checkouts/PerfectLib/Sources/PerfectLib/Dir.swift:64:10: error: cannot find 'access' in scope
                return access(path, F_OK) != -1
                       ^~~~~~
/tmp/Perfect-NIO/.build/checkouts/PerfectLib/Sources/PerfectLib/Dir.swift:91:13: error: cannot find 'rmdir' in scope
                let res = rmdir(realPath)
                          ^~~~~
/tmp/Perfect-NIO/.build/checkouts/PerfectLib/Sources/PerfectLib/Dir.swift:131:19: error: cannot find 'readdir' in scope
                guard let ent = readdir(d) else {
                                ^~~~~~~
/tmp/Perfect-NIO/.build/checkouts/PerfectLib/Sources/PerfectLib/Dir.swift:147:19: error: cannot find 'opendir' in scope
                guard let dir = opendir(realPath) else {
                                ^~~~~~~
/tmp/Perfect-NIO/.build/checkouts/PerfectLib/Sources/PerfectLib/Dir.swift:151:11: error: cannot find 'closedir' in scope
```

**Comment by eneisyou** [comment]
仓库已弃用了吧

**Comment by taplin** [comment]
Rockford, if you are still interested, take a look at the updated versions and let me know if we need to do something more to bring it up for current linux builds.
